### ISSUE TITLE
Be sure we have template, getting error when I use repeater matrix with combo field and page edit children

### ISSUE THREAD

**Issue by trk** [adrianbj/CustomUploadNames#10]
https://github.com/adrianbj/CustomUploadNames/blob/066592857914b11cfa4fe0e54d7a7f213e54d752/ProcessCustomUploadNames.module.php#L113

manually update condition
```php
if(!isset($process->getPage()->template) || $process->getPage()->template == 'language')
```

**Comment by adrianbj** [comment]
Thanks @trk - I've added your fix to the latest version.
