### ISSUE TITLE
Feature request: Add web-friendly file naming format

### ISSUE THREAD

**Issue by lesaff** [adrianbj/CustomUploadNames#2]
@adrianbj, nice module!

It would be nice to add `web-friendly` file format as one of the options.

Thx
Rudy

**Comment by adrianbj** [comment]
Hi @lesaff - glad you like it.

Not sure exactly what you mean though - ProcessWire itself already lowercases and removes spaces from filenames. Is there something else in particular you would like it to take care of?

**Comment by lesaff** [comment]
No way, I didn't know that. I'll close this. Thanks for your quick response.
